enabled = true;
path = "/var/rspamd/dkim/$domain.$selector.key";
selector = "mail";
allow_envfrom_empty = true;
allow_hdrfrom_mismatch = false;
sign_networks = ["10.44.0.0/24", "127.0.0.0/8"];
use_domain = "header";
