-r -- enabled = true;
-r -- path = "/var/rspamd/dkim/$domain.$selector.key";
-r -- selector = "mail";
-r -- allow_envfrom_empty = true;
-r -- allow_hdrfrom_mismatch = false;
-r -- sign_networks = ["10.44.0.0/24", "127.0.0.0/8"];
-r -- use_domain = "header";
