user  www www;
worker_processes  auto;

# Unified nginx error log for all vhosts/sites.
error_log  /var/log/nginx/mail.error.log;
pid        /var/run/nginx.pid;

events {
    worker_connections  1024;
}

http {
    # Unified nginx access log for all vhosts/sites.
    access_log  /var/log/nginx/mail.access.log;

    # Global HTTP snippets
    include /etc/nginx/conf-enabled/*.conf;

    # Virtual hosts
    include /etc/nginx/sites-enabled/*.conf;
}
