# openbsd-mailstack monitoring managed block
/var/log/openbsd-mailstack-monitor.log                root:wheel  644  14  2000  *  Z
/var/log/openbsd-mailstack-cron-report.log           root:wheel  644  14  2000  *  Z
