bind 127.0.0.1
port 6379
protected-mode yes
tcp-backlog 128
timeout 0
tcp-keepalive 300
daemonize yes
supervised no
loglevel notice
logfile /var/log/redis/redis.log
databases 16
save 900 1
save 300 10
save 60 10000
stop-writes-on-bgsave-error yes
rdbcompression yes
rdbchecksum yes
dbfilename dump.rdb
dir /var/redis
maxmemory 0
appendonly no
