-r -- # HTTP vhost, mainly for ACME and redirect to HTTPS
-r -- 
-r -- server {
-r --     listen 80;
-r --     listen [::]:80;
-r -- 
-r --     server_name _;
-r -- 
-r --     # Allow ACME challenge over HTTP without redirect
-r --     # nginx chroot: /var/www, so alias /acme/ -> /var/www/acme on disk
-r --     location ^~ /.well-known/acme-challenge/ {
-r --         alias /acme/;
-r --         try_files $uri =404;
-r --         allow all;
-r --     }
-r -- 
-r --     # Redirect all other HTTP traffic to HTTPS
-r --     location / {
-r --         return 301 https://$host$request_uri;
-r --     }
-r -- }
