-r -- mail_location = maildir:/var/vmail/%d/%n
-r -- mail_uid = 2000
-r -- mail_gid = 2000
-r -- first_valid_uid = 2000
-r -- last_valid_uid = 2000
-r -- ssl = required
-r -- ssl_cert = </etc/ssl/mail.example.com.fullchain.pem
-r -- ssl_key = </etc/ssl/private/mail.example.com.key
-r -- auth_mechanisms = plain login
-r -- passdb {
-r --   driver = sql
-r --   args = /etc/dovecot/dovecot-sql.conf.ext
-r -- }
-r -- userdb {
-r --   driver = static
-r --   args = uid=2000 gid=2000 home=/var/vmail/%d/%n
-r -- }
-r -- service auth {
-r --   unix_listener /var/spool/postfix/private/auth {
-r --     mode = 0660
-r --     user = _postfix
-r --     group = _postfix
-r --   }
-r -- }
-r -- service lmtp {
-r --   unix_listener /var/spool/postfix/private/dovecot-lmtp {
-r --     mode = 0600
-r --     user = _postfix
-r --     group = _postfix
-r --   }
-r -- }
-r -- protocol lmtp {
-r --   postmaster_address = postmaster@example.com
-r -- }
-r -- plugin {
-r --   sieve_before = /etc/dovecot/sieve-before
-r -- }
